name: Build PRs
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m")" >> $GITHUB_OUTPUT
        shell: bash
      - name: Cache Maven Dependencies
        id: maven-deps-cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-maven-deps
          path: |
            git-common/pom.xml
      - name: Maven Dependencies
        if: steps.maven-deps-cache.outputs.cache-hit != 'true'
        run: |
          mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
      - name: Upload Unsigned Module
        uses: actions/upload-artifact@v3
        with:
          name: ignition-extensions-unsigned
          path: git-build/target/Git-unsigned.modl
          if-no-files-found: error
